spring.datasource.url=jdbc:h2:mem:magiadata
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# Configuración de Swagger UI
springdoc.swagger-ui.url=/api/openapi.json
springdoc.swagger-ui.path=/swagger-ui.html

# Mover Jersey a /api para no bloquear recursos estáticos ni MVC
spring.jersey.application-path=/api

# Reto 1: Configurar puerto
# Los estudiantes deberán descomentar y configurar el puerto 8080 para arrancar el servidor
# server.port=8080

spring.jersey.application-path=/api
